name: Publish to VS Marketplace

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish release to marketplace
        id: publish
        uses: mrluje/vs-marketplace-publisher@v2
        with:
          # (Required) Personal access token to perform action on the VS Marketplace.
          pat: ${{ secrets.vs_pat }}

          # (Required) Path to the manifest used for the publish
          manifestPath: vs-extension/vsixManifest.json
